INSERT INTO "AvailableDocuments" (
doc_id,
"updatedAt",
"createdAt",
html_id,
certification_notes,
delete_additional_notes,
legislation_allowed,
photocopy_allowed,
certification_required,
doc_type_id,
doc_title,
doc_title_start,
doc_title_mid,
additional_detail,
eligible_check_option_1,
eligible_check_option_2,
eligible_check_option_3,
legalisation_clause,
kind_of_document,
extra_title_text,
synonyms,
accept_text,
eligible_check_option_4,
eligible_check_option_5,
eligible_check_option_6
)
VALUES (
    '261',
null,
null,
'adoption_document',
null,
null,
'true',
'true',
'true',
'3',
'Adoption Document',
'Adoption document',
'UK adoption document',
null,
'Your original document stamped or sealed in wet ink by the court, or signed by an official of the court or a judge',
'Your original document not stamped or sealed or signed by a court or an official of the court  <span>certification required</span>',
'A photocopy <span>certification required</span> of your *replaceme*  <span>certification required</span>',
'can be legalised',
'Document',
null,
'personal, identity, identification, ID, adoption, court, adopt',
'We accept the document in the following formats. Please confirm which one you will send:',
'A print out of your *replaceme* which has been produced as a PDF/electronic document. The document may contain an electronic/digital signature or seal <span>certification required</span>',
null,
null
);
