TRUNCATE TABLE country;
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (1, 'Afghanistan', false, 'Afghanistan');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (2, 'Akrotiri', true, 'Cyprus');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (3, 'Albania', false, 'Albania');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (4, 'Algeria', false, 'Algeria');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (5, 'Andorra', true, 'Andorra');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (6, 'Angola', false, 'Angola');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (7, 'Anguilla', false, 'Anguilla');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (8, 'Antigua and Barbuda', false, 'Antigua and Barbuda');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (9, 'Argentina', false, 'Argentina');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (10, 'Armenia', false, 'Armenia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (11, 'Aruba', false, 'Aruba');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (12, 'Australia', false, 'Australia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (13, 'Austria', true, 'Austria');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (14, 'Azerbaijan', false, 'Azerbaijan');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (15, 'Bahrain', false, 'Bahrain');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (16, 'Bangladesh', false, 'Bangladesh');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (17, 'Barbados', false, 'Barbados');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (18, 'Belarus', false, 'Belarus');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (19, 'Belgium', true, 'Belgium');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (20, 'Belize', false, 'Belize');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (21, 'Benin', false, 'Benin');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (22, 'Bermuda', false, 'Bermuda');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (23, 'Bhutan', false, 'Bhutan');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (24, 'Bolivia', false, 'Bolivia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (25, 'Bonaire/St Eustatius/Saba', false, 'Bonaire,  Sint Eustatius and Saba');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (26, 'Bosnia and Herzegovina', false, 'Bosnia and Herzegovina');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (27, 'Botswana', false, 'Botswana');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (28, 'Brazil', false, 'Brazil');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (29, 'British Indian Ocean Territory', false, 'British Indian Ocean Territory');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (30, 'British Virgin Islands', false, 'British Virgin Islands');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (31, 'Brunei', false, 'Brunei');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (32, 'Bulgaria', true, 'Bulgaria');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (33, 'Burkina Faso', false, 'Burkina Faso');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (34, 'Burundi', false, 'Burundi');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (35, 'Cambodia', false, 'Cambodia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (36, 'Cameroon', false, 'Cameroon');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (37, 'Canada', false, 'Canada');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (38, 'Cape Verde', false, 'Cape Verde');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (39, 'Cayman Islands', false, 'Cayman Islands');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (40, 'Central African Republic', false, 'Central African Republic');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (41, 'Chad', false, 'Chad');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (42, 'Chile', false, 'Chile');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (43, 'China', false, 'China');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (44, 'Colombia', false, 'Colombia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (45, 'Comoros', false, 'Comoros');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (46, 'Congo', false, 'Congo');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (47, 'Congo (Democratic Republic)', false, 'Congo, Democratic Republic');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (48, 'Costa Rica', false, 'Costa Rica');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (49, 'Croatia', true, 'Croatia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (50, 'Cuba', false, 'Cuba');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (51, 'Curaçao', false, 'Curaçao');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (52, 'Cyprus', true, 'Cyprus');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (53, 'Czech Republic', true, 'Czech Republic');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (54, 'Denmark', true, 'Denmark');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (55, 'Dhekelia', true, 'Cyprus');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (56, 'Djibouti', false, 'Djibouti');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (57, 'Dominica', false, 'Dominica');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (58, 'Dominican Republic', false, 'Dominican Republic');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (59, 'East Timor', false, 'Timor-Leste');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (60, 'Ecuador', false, 'Ecuador');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (61, 'Egypt', false, 'Egypt');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (62, 'El Salvador', false, 'El Salvador');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (63, 'Equatorial Guinea', false, 'Equatorial Guinea');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (64, 'Eritrea', false, 'Eritrea');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (65, 'Estonia', true, 'Estonia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (66, 'Eswatini', false, 'Swaziland');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (67, 'Ethiopia', false, 'Ethiopia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (68, 'Falkland Islands', false, 'Falkland Islands');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (69, 'Fiji', false, 'Fiji');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (70, 'Finland', true, 'Finland');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (71, 'France', true, 'France');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (72, 'French Guiana', false, 'French Guiana');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (73, 'French Polynesia', false, 'French Polynesia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (74, 'Gabon', false, 'Gabon');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (75, 'Georgia', false, 'Georgia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (76, 'Germany', true, 'Germany');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (77, 'Ghana', false, 'Ghana');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (78, 'Gibraltar', true, 'Gibraltar');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (79, 'Greece', true, 'Greece');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (80, 'Grenada', false, 'Grenada');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (81, 'Guadeloupe', false, 'Guadeloupe');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (82, 'Guatemala', false, 'Guatemala');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (83, 'Guinea', false, 'Guinea');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (84, 'Guinea-Bissau', false, 'Guinea-Bissau');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (85, 'Guyana', false, 'Guyana');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (86, 'Haiti', false, 'Haiti');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (87, 'Honduras', false, 'Honduras');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (88, 'Hong Kong', false, 'Hong Kong');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (89, 'Hungary', true, 'Hungary');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (90, 'Iceland', true, 'Iceland');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (91, 'India', false, 'India');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (92, 'Indonesia', false, 'Indonesia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (93, 'Iran', false, 'Iran');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (94, 'Iraq', false, 'Iraq');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (95, 'Ireland', true, 'Ireland');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (96, 'Israel', false, 'Israel');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (97, 'Italy', true, 'Italy');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (98, 'Ivory Coast', false, 'Côte d''Ivoire');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (99, 'Jamaica', false, 'Jamaica');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (100, 'Japan', false, 'Japan');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (101, 'Jordan', false, 'Jordan');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (102, 'Kazakhstan', false, 'Kazakhstan');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (103, 'Kenya', false, 'Kenya');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (104, 'Kiribati', false, 'Kiribati');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (105, 'Kosovo', false, 'Kosovo');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (106, 'Kuwait', false, 'Kuwait');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (107, 'Kyrgyzstan', false, 'Kyrgyzstan');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (108, 'Laos', false, 'Laos');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (109, 'Latvia', true, 'Latvia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (110, 'Lebanon', false, 'Lebanon');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (111, 'Lesotho', false, 'Lesotho');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (112, 'Liberia', false, 'Liberia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (113, 'Libya', false, 'Libya');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (114, 'Liechtenstein', false, 'Liechtenstein');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (115, 'Lithuania', true, 'Lithuania');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (116, 'Luxembourg', true, 'Luxembourg');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (117, 'Macao', false, 'Macao');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (118, 'Madagascar', false, 'Madagascar');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (119, 'Malawi', false, 'Malawi');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (120, 'Malaysia', false, 'Malaysia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (121, 'Maldives', false, 'Maldives');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (122, 'Mali', false, 'Mali');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (123, 'Malta', true, 'Malta');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (124, 'Marshall Islands', false, 'Marshall Islands');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (125, 'Martinique', false, 'Martinique');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (126, 'Mauritania', false, 'Mauritania');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (127, 'Mauritius', false, 'Mauritius');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (128, 'Mayotte', false, 'Mayotte');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (129, 'Mexico', false, 'Mexico');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (130, 'Micronesia', false, 'Micronesia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (131, 'Moldova', false, 'Moldova');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (132, 'Monaco', true, 'Monaco');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (133, 'Mongolia', false, 'Mongolia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (134, 'Montenegro', false, 'Montenegro');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (135, 'Montserrat', false, 'Montserrat');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (136, 'Morocco', false, 'Morocco');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (137, 'Mozambique', false, 'Mozambique');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (138, 'Myanmar', false, 'Burma');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (139, 'Namibia', false, 'Namibia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (140, 'Nauru', false, 'Nauru');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (141, 'Nepal', false, 'Nepal');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (142, 'Netherlands', true, 'Netherlands');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (143, 'New Caledonia', false, 'New Caledonia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (144, 'New Zealand', false, 'New Zealand');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (145, 'Nicaragua', false, 'Nicaragua');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (146, 'Niger', false, 'Niger');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (147, 'Nigeria', false, 'Nigeria');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (148, 'North Korea', false, 'North Korea');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (149, 'North Macedonia', false, 'Macedonia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (150, 'Norway', true, 'Norway');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (151, 'Oman', false, 'Oman');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (152, 'Pakistan', false, 'Pakistan');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (153, 'Palau', false, 'Palau');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (154, 'Panama', false, 'Panama');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (155, 'Papua New Guinea', false, 'Papua New Guinea');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (156, 'Paraguay', false, 'Paraguay');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (157, 'Peru', false, 'Peru');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (158, 'Philippines', false, 'Philippines');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (159, 'Pitcairn, Henderson, Ducie and Oeno Islands', false, 'Pitcairn Island');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (160, 'Poland', true, 'Poland');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (161, 'Portugal', true, 'Portugal');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (162, 'Qatar', false, 'Qatar');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (163, 'Réunion', false, 'Réunion');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (164, 'Romania', true, 'Romania');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (165, 'Russia', false, 'Russia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (166, 'Rwanda', false, 'Rwanda');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (167, 'Saint-Barthélemy', false, 'Saint Barthélemy');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (168, 'Samoa', false, 'Samoa');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (169, 'San Marino', true, 'San Marino');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (170, 'Sao Tome and Principe', false, 'São Tomé and Príncipe');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (171, 'Saudi Arabia', false, 'Saudi Arabia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (172, 'Senegal', false, 'Senegal');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (173, 'Serbia', false, 'Serbia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (174, 'Seychelles', false, 'Seychelles');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (175, 'Sierra Leone', false, 'Sierra Leone');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (176, 'Singapore', false, 'Singapore');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (177, 'Slovakia', true, 'Slovakia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (178, 'Slovenia', true, 'Slovenia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (179, 'Solomon Islands', false, 'Solomon Islands');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (180, 'Somalia', false, 'Somalia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (181, 'South Africa', false, 'South Africa');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (182, 'South Georgia and South Sandwich Islands', false, 'South Georgia and South Sandwich Islands');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (183, 'South Korea', false, 'South Korea');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (184, 'South Sudan', false, 'South Sudan');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (185, 'Spain', true, 'Spain');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (186, 'Sri Lanka', false, 'Sri Lanka');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (187, 'St Helena, Ascension and Tristan da Cunha', false, 'Saint Helena,  Ascension and Tristan da Cunha');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (188, 'St Kitts and Nevis', false, 'Saint Kitts and Nevis');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (189, 'St Lucia', false, 'Saint Lucia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (190, 'St Maarten', false, 'St Maarten');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (191, 'St Martin', false, 'St Martin');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (192, 'St Pierre & Miquelon', false, 'St. Pierre and Miquelon');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (193, 'St Vincent', false, 'Saint Vincent and the Grenadines');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (194, 'Sudan', false, 'Sudan');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (195, 'Suriname', false, 'Suriname');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (196, 'Sweden', true, 'Sweden');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (197, 'Switzerland', true, 'Switzerland');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (198, 'Syria', false, 'Syria');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (199, 'Taiwan', false, 'Taiwan');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (200, 'Tajikistan', false, 'Tajikistan');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (201, 'Tanzania', false, 'Tanzania');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (202, 'Thailand', false, 'Thailand');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (203, 'The Bahamas', false, 'Bahamas');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (204, 'The Gambia', false, 'Gambia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (205, 'The Occupied Palestinian Territories', false, 'The Occupied Palestinian Territories');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (206, 'Togo', false, 'Togo');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (207, 'Tonga', false, 'Tonga');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (208, 'Trinidad and Tobago', false, 'Trinidad and Tobago');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (209, 'Tunisia', false, 'Tunisia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (210, 'Turkey', false, 'Turkey');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (211, 'Turkmenistan', false, 'Turkmenistan');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (212, 'Turks and Caicos Islands', false, 'Turks and Caicos Islands');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (213, 'Tuvalu', false, 'Tuvalu');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (214, 'Uganda', false, 'Uganda');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (215, 'Ukraine', false, 'Ukraine');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (216, 'United Arab Emirates', false, 'United Arab Emirates');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (217, 'United Kingdom', true, 'United Kingdom');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (218, 'United States', false, 'United States');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (219, 'Uruguay', false, 'Uruguay');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (220, 'Uzbekistan', false, 'Uzbekistan');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (221, 'Vanuatu', false, 'Vanuatu');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (222, 'Vatican City', true, 'Vatican City');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (223, 'Venezuela', false, 'Venezuela');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (224, 'Vietnam', false, 'Vietnam');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (225, 'Wallis and Futuna', false, 'Wallis and Futuna Islands');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (226, 'Western Sahara', false, 'Western Sahara');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (227, 'Yemen', false, 'Yemen');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (228, 'Zambia', false, 'Zambia');
INSERT INTO country (id, name, "in_EU", casebook_mapping) VALUES (229, 'Zimbabwe', false, 'Zimbabwe');



