/**
* Model Application.js
* @module Model Application
*/
var Sequelize = require('sequelize');

module.exports = {
    attributes: {
        // id: {
        //   type: 'number',
        //   columnName: 'application_id',
        //   autoIncrement: true
        // },
        id: {
            type: 'number',
            allowNull: false,
            autoIncrement: true,
            columnName: 'application_id',
            // _autoGenerated: true
        },
        user_id: {
            type: 'number',
            allowNull: true
        },
        unique_app_id: {
            type: 'string'
        },
        submitted: {
            type: 'string',
            allowNull: true,
            defaultsTo: 'draft'
        },
        serviceType: {
            type: 'string',
            allowNull: false,
            // validate: {
            //     notContains: {
            //         args: 'not ok',
            //         msg: JSON.stringify([{
            //             "questionId" : 'service_type_selector',  // ID of the question container, taken from your HTML
            //             "errInfo": 'A service type has not been chosen',  // Detail of hte error, i.e. what the error is
            //             "errSoltn": 'Please select a service type to use and click Continue'  // Detail of how to solve error, i.e. how to fix and move to next page
            //         }])
            //     }
            // }
        },
        feedback_consent: {
            type: 'boolean',
            allowNull: false,
            // validate: {
            //     notEmpty: {
            //         msg: JSON.stringify([{
            //             "questionId" : 'feedback_consent',  // ID of the question container, taken from your HTML
            //             "errInfo": 'You must confirm giving feedback consent',  // Detail of hte error, i.e. what the error is
            //             "errSoltn": 'Tell us whether we can contact you for feedback'  // Detail of how to solve error, i.e. how to fix and move to next page
            //         }])
            //     }
            // }
        },
      residency: {
        type: 'boolean',
        allowNull: false,
        // validate: {
        //   notEmpty: {
        //     msg: JSON.stringify([{
        //       "questionId" : 'residency',  // ID of the question container, taken from your HTML
        //       "errInfo": 'You must confirm if your application is about residency',  // Detail of hte error, i.e. what the error is
        //       "errSoltn": 'Tell us if your application is about residency'  // Detail of how to solve error, i.e. how to fix and move to next page
        //     }])
        //   }
        // }
      },
      doc_reside_EU: {
        type: 'boolean',
        allowNull: false,
        // validate: {
        //   notEmpty: {
        //     msg: JSON.stringify([{
        //       "questionId" : 'doc_reside_EU',  // ID of the question container, taken from your HTML
        //       "errInfo": 'You must confirm if your document is residing in the EU',  // Detail of hte error, i.e. what the error is
        //       "errSoltn": 'Tell us if your document is residing in the EU'  // Detail of how to solve error, i.e. how to fix and move to next page
        //     }])
        //   }
        // }
      },
        all_info_correct: {
           type: 'boolean',
            allowNull: false,
            // validate: {
            //     notEmpty: {
            //         msg: JSON.stringify([{
            //             "questionId" : 'all_info_correct',  // ID of the question container, taken from your HTML
            //             "errInfo": 'You have not confirmed that all the information you have provided is correct',  // Detail of hte error, i.e. what the error is
            //             "errSoltn": 'Confirm that the information you\'ve given is correct and that you agree to the terms'  // Detail of how to solve error, i.e. how to fix and move to next page
            //         }])
            //     },
            //     notContains: {
            //         args: 'not ok',
            //         msg: JSON.stringify([{
            //             "questionId": 'all_info_correct',  // ID of the question container, taken from your HTML
            //             "errInfo": 'You haven\'t confirmed that all the information you’ve given us is correct',  // Detail of hte error, i.e. what the error is
            //             "errSoltn": 'Confirm that the information you\'ve given is correct and that you agree to the terms'  // Detail of how to solve error, i.e. how to fix and move to next page
            //         }])
            //     }
            // }
        },
        application_reference: {
            type: 'string',
            allowNull: true
        },
        case_reference: {
            type: 'string',
            allowNull: true
        },
        application_guid: {
          type: 'string'
        },
        application_start_date: {
            type: 'ref',
            columnType: 'timestamp',
            // allowNull: true
        },
        company_name: {
            type: 'string',
            allowNull: true
        }
    },
    options: {
        tableName: 'Application',
    }
};

